"""empty message

Revision ID: 6a3466af149d
Revises: 698c20678b0d
Create Date: 2021-06-09 23:33:25.147198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3466af149d'
down_revision = '698c20678b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('short_description', sa.String(length=50), nullable=False),
    sa.Column('blog_posted', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=20), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userpost')
    # ### end Alembic commands ###
